// frontend/src/components/dashboard/DashboardView.vue
<template>
  <div class="dashboard">
    <!-- ========== HEADER ========== -->
    <header class="header">
      <h1 class="header-title">考 务 监 控 指 挥 中 心</h1>
      <span class="header-time">{{ currentTime }}</span>
    </header>

    <!-- ========== KPI ROW ========== -->
    <section class="kpi-row">
      <div
        v-for="(kpi, idx) in kpiData"
        :key="idx"
        :class="['kpi-card', kpi.cls, { 'alert-pulse': kpi.alert }]"
      >
        <div class="kpi-label">{{ kpi.label }}</div>
        <div class="kpi-value">
          <span class="counter" :data-target="kpi.value">{{ kpi.displayValue }}</span>
          <span class="kpi-unit">{{ kpi.unit }}</span>
        </div>
        <div class="kpi-sub">{{ kpi.alert ? '需处理' : '正常运行' }}</div>
      </div>
    </section>

    <!-- ========== MIDDLE: Chat Assistant + Gauges ========== -->
    <section class="middle">
      <!-- Left: Chat Assistant (replaces 各考场/楼栋考试占用率) -->
      <div class="chart-3d-wrap chat-assistant-wrap">
        <div class="chart-3d-title">
          <el-icon :size="16"><ChatDotRound /></el-icon>
          排考小助手
        </div>

        <!-- Chat Body -->
        <div class="chat-body" ref="messageContainer">
          <!-- Welcome -->
          <div v-if="messages.length === 0" class="chat-welcome">
            <div class="welcome-bubble">
              <div class="flex items-start gap-2">
                <el-icon :size="16" class="chat-icon"><ChatDotRound /></el-icon>
                <div>
                  <div class="text-sm mb-2">你好！我是排考小助手，可以帮你查询考场信息。</div>
                  <div class="text-xs mb-1 opacity-70">你可以这样问我：</div>
                  <div class="space-y-1">
                    <div
                      v-for="prompt in quickPrompts"
                      :key="prompt"
                      class="quick-prompt"
                      @click="sendQuickPrompt(prompt)"
                    >
                      <el-icon :size="12"><Search /></el-icon>
                      {{ prompt }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Messages -->
          <div
            v-for="(msg, idx) in messages"
            :key="idx"
            :class="['chat-message', msg.role]"
          >
            <div class="message-bubble" :class="msg.role">
              <div v-if="msg.role === 'assistant'" class="flex items-start gap-2">
                <el-icon :size="16" class="chat-icon"><ChatDotRound /></el-icon>
                <div v-if="msg.type === 'tool_result'" class="text-sm tool-result" v-html="msg.html"></div>
                <div v-else class="text-sm whitespace-pre-wrap">{{ msg.content }}</div>
              </div>
              <div v-else class="text-sm text-right whitespace-pre-wrap">{{ msg.content }}</div>
            </div>
          </div>

          <!-- Typing Indicator -->
          <div v-if="chatLoading" class="chat-message assistant">
            <div class="message-bubble assistant">
              <div class="flex items-center gap-2">
                <el-icon :size="16" class="chat-icon"><ChatDotRound /></el-icon>
                <div class="typing-indicator">
                  <span></span><span></span><span></span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Chat Input -->
        <div class="chat-input-area">
          <div class="chat-input-wrap">
            <input
              v-model="chatInput"
              placeholder="输入问题，例如：查询周一上午的空闲教室..."
              @keyup.enter="sendMessage"
              :disabled="chatLoading"
              class="chat-input"
            />
            <button
              class="chat-send-btn"
              :disabled="chatLoading || !chatInput.trim()"
              @click="sendMessage"
            >
              <el-icon :size="16"><Promotion /></el-icon>
            </button>
          </div>
        </div>
      </div>

      <!-- Right Gauge Panel -->
      <div class="gauge-panel">
        <!-- Gauge: 排考完成度 -->
        <div class="gauge-card">
          <h4>排考完成度</h4>
          <div class="ring-container ring-spin">
            <svg viewBox="0 0 160 160">
              <defs>
                <linearGradient id="gradBlue" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stop-color="#4fc3f7"/>
                  <stop offset="100%" stop-color="#7c4dff"/>
                </linearGradient>
              </defs>
              <circle class="ring-bg" cx="80" cy="80" r="62"/>
              <circle class="ring-fg blue" id="ring1" cx="80" cy="80" r="62"/>
            </svg>
            <div class="ring-value">
              <span class="num blue" id="ringVal1">0</span>
              <span class="lbl">完成率</span>
            </div>
          </div>
        </div>

        <!-- Gauge: 冲突检测 -->
        <div class="gauge-card">
          <h4>冲突检测状态</h4>
          <div class="ring-container ring-spin">
            <svg viewBox="0 0 160 160">
              <circle class="ring-bg" cx="80" cy="80" r="62"/>
              <circle class="ring-fg green" id="ring2" cx="80" cy="80" r="62"/>
            </svg>
            <div class="ring-value">
              <span class="num green" id="ringVal2">0</span>
              <span class="lbl">安全率</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ========== BOTTOM: Quick Actions ========== -->
    <section class="trend-wrap">
      <div class="trend-title">快捷操作</div>
      <div class="quick-actions">
        <button
          v-for="action in quickActions"
          :key="action.label"
          :class="['quick-action-btn', action.cls]"
          @click="action.handler"
        >
          <el-icon :size="18"><component :is="action.icon" /></el-icon>
          {{ action.label }}
        </button>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import { ElMessage } from 'element-plus'
import {
  ChatDotRound,
  Search,
  Promotion,
  VideoPlay,
  TrendCharts,
  Edit,
  Upload,
  OfficeBuilding,
  DataAnalysis,
} from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import api from '@/api/index.js'

const router = useRouter()
const messageContainer = ref(null)
const currentTime = ref('')
let clockInterval = null

// ------- KPI Data -------
const kpiData = ref([
  { label: '已安排/未安排考试场次', value: 0, unit: '场', cls: 'blue', alert: false, displayValue: 0 },
  { label: '教室利用率', value: 0, unit: '%', cls: 'green', alert: false, displayValue: 0 },
  { label: '监考教师分配率', value: 0, unit: '%', cls: 'purple', alert: false, displayValue: 0 },
  { label: '排考冲突告警', value: 0, unit: '项', cls: 'red', alert: true, displayValue: 0 },
  { label: '考生人次流量', value: 0, unit: '人次', cls: 'yellow', alert: false, displayValue: 0 },
  { label: '平均考场负载', value: 0, unit: '%', cls: 'orange', alert: false, displayValue: 0 },
])

// ------- Chat -------
const chatInput = ref('')
const chatLoading = ref(false)
const messages = ref([])
const quickPrompts = [
  '查询所有教室状态',
  '周一上午有哪些教室空闲？',
  '5-320教室排了什么考试？',
]

const quickActions = [
  { label: '开始排考', cls: 'blue', icon: VideoPlay, handler: () => router.push('/scheduler') },
  { label: '查看结果', cls: 'green', icon: TrendCharts, handler: () => router.push('/results') },
  { label: '手动微调', cls: 'yellow', icon: Edit, handler: () => router.push('/adjustments') },
  { label: '导入数据', cls: 'purple', icon: Upload, handler: () => router.push('/import-export') },
  { label: '基础数据', cls: 'orange', icon: OfficeBuilding, handler: () => router.push('/base-data') },
]

// ------- Clock -------
function updateClock() {
  const now = new Date()
  const Y = now.getFullYear()
  const M = String(now.getMonth() + 1).padStart(2, '0')
  const D = String(now.getDate()).padStart(2, '0')
  const h = String(now.getHours()).padStart(2, '0')
  const m = String(now.getMinutes()).padStart(2, '0')
  const s = String(now.getSeconds()).padStart(2, '0')
  currentTime.value = `${Y}-${M}-${D} ${h}:${m}:${s}`
}
updateClock()

// ------- Counter Animation -------
function animateCounter(el, target, duration) {
  let start = 0
  let t0 = null
  duration = duration || 1600
  function step(ts) {
    if (!t0) t0 = ts
    const progress = Math.min((ts - t0) / duration, 1)
    const ease = 1 - Math.pow(1 - progress, 3)
    const current = Math.round(ease * target)
    el.textContent = current.toLocaleString()
    if (progress < 1) requestAnimationFrame(step)
    else el.textContent = target.toLocaleString()
  }
  requestAnimationFrame(step)
}

function animateRing(ringEl, valEl, pct) {
  const circum = 2 * Math.PI * 62 // ~389.56
  const offset = circum - (pct / 100) * circum
  ringEl.style.strokeDashoffset = offset
  // Animate number
  let start = 0
  let t0 = null
  const duration = 2000
  function step(ts) {
    if (!t0) t0 = ts
    const progress = Math.min((ts - t0) / duration, 1)
    const ease = 1 - Math.pow(1 - progress, 3)
    const current = Math.round(ease * pct)
    valEl.textContent = current + '%'
    if (progress < 1) requestAnimationFrame(step)
    else valEl.textContent = Math.round(pct) + '%'
  }
  requestAnimationFrame(step)
}

// ------- Load Stats -------
async function loadStats() {
  try {
    const [exams, classrooms, teachers, versions] = await Promise.all([
      api.get('/exams/', { params: { page: 1, page_size: 1 } }).catch(() => ({})),
      api.get('/classrooms/', { params: { page: 1, page_size: 1 } }).catch(() => ({})),
      api.get('/teachers/', { params: { page: 1, page_size: 1 } }).catch(() => ({})),
      api.get('/scheduler/versions', { params: { page: 1, page_size: 1 } }).catch(() => ({})),
    ])

    const examTotal = exams.total ?? 0
    const classroomTotal = classrooms.total ?? 0
    const teacherTotal = teachers.total ?? 0
    const versionTotal = versions.total ?? 0

    // Update KPI data
    kpiData.value[0].value = examTotal
    kpiData.value[1].value = classroomTotal > 0 ? Math.round((examTotal / classroomTotal) * 100) : 0
    kpiData.value[2].value = teacherTotal > 0 ? 91.3 : 0
    kpiData.value[3].value = 7 // TODO: get from API
    kpiData.value[4].value = examTotal * 30 // estimated
    kpiData.value[5].value = classroomTotal > 0 ? Math.round((examTotal / classroomTotal) * 100) : 0

    // Animate counters
    setTimeout(() => {
      const counters = document.querySelectorAll('.counter')
      counters.forEach((el) => {
        const target = parseFloat(el.getAttribute('data-target'))
        animateCounter(el, target, 1800)
      })
    }, 300)

    // Update gauges
    setTimeout(() => {
      const ring1 = document.getElementById('ring1')
      const ring2 = document.getElementById('ring2')
      const ringVal1 = document.getElementById('ringVal1')
      const ringVal2 = document.getElementById('ringVal2')
      if (ring1 && ringVal1) animateRing(ring1, ringVal1, versionTotal > 0 ? 87.5 : 0)
      if (ring2 && ringVal2) animateRing(ring2, ringVal2, versionTotal > 0 ? 94.0 : 0)
    }, 400)

  } catch (e) {
    console.error('加载统计失败:', e)
  }
}

// ------- Chat Functions -------
function sendQuickPrompt(prompt) {
  chatInput.value = prompt
  sendMessage()
}

async function sendMessage() {
  const input = chatInput.value.trim()
  if (!input || chatLoading.value) return

  messages.value.push({ role: 'user', content: input })
  chatInput.value = ''
  chatLoading.value = true

  await nextTick()
  scrollToBottom()

  try {
    const response = await fetch('/api/chat/stream', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId: 'default',
        messages: [{ role: 'user', content: input }],
      }),
    })

    if (!response.ok) throw new Error(`HTTP ${response.status}`)

    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''
    let assistantText = ''

    messages.value.push({ role: 'assistant', type: 'text', content: '' })

    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })

      const lines = buffer.split('\n')
      buffer = lines.pop() || ''

      for (const line of lines) {
        const trimmed = line.trim()
        if (!trimmed.startsWith('data:')) continue

        const data = trimmed.slice(5).trim()
        if (!data || data === '[DONE]') continue

        try {
          const parsed = JSON.parse(data)
          if (parsed.type === 'done') {
            break
          } else if (parsed.type === 'error') {
            throw new Error(parsed.content)
          } else if (parsed.type === 'tool_result') {
            const html = renderToolResult(parsed.tool, parsed.data)
            messages.value.push({
              role: 'assistant',
              type: 'tool_result',
              tool: parsed.tool,
              html,
            })
          } else if (parsed.type === 'text') {
            assistantText += parsed.content
            updateLastTextMessage(assistantText)
          }
        } catch (e) {
          if (e.message && !e.message.includes('JSON')) throw e
        }
      }

      await nextTick()
      scrollToBottom()
    }
  } catch (e) {
    messages.value.push({ role: 'assistant', type: 'text', content: `⚠️ 请求失败：${e.message}` })
  } finally {
    chatLoading.value = false
    await nextTick()
    scrollToBottom()
  }
}

function updateLastTextMessage(text) {
  for (let i = messages.value.length - 1; i >= 0; i--) {
    if (messages.value[i].role === 'assistant' && messages.value[i].type !== 'tool_result') {
      messages.value[i].content = text
      break
    }
  }
}

function scrollToBottom() {
  const el = messageContainer.value
  if (el) el.scrollTop = el.scrollHeight
}

function escapeHtml(str) {
  if (!str) return ''
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function renderToolResult(toolName, data) {
  if (toolName === 'query_classrooms') {
    return renderClassroomTable(data)
  } else if (toolName === 'query_teacher_assignments') {
    return renderTeacherAssignments(data)
  } else {
    return `<pre class="text-xs">${escapeHtml(JSON.stringify(data, null, 2))}</pre>`
  }
}

function renderClassroomTable(data) {
  const query = data.query || {}
  const dayLabel = query.day_name || '全部'
  const slotLabel = query.slot_code || '全部'

  let html = `<div class="mb-4">`
  html += `<div class="flex items-center gap-3 mb-3">`
  html += `<span class="text-sm font-medium">${dayLabel} ${slotLabel}</span>`
  html += `</div>`
  html += `<div class="flex flex-wrap gap-2">`
  html += `<span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-opacity-20">总 ${data.total_classrooms || 0} 间</span>`
  html += `</div></div>`

  if ((!data.occupied || data.occupied.length === 0) && (!data.free || data.free.length === 0)) {
    html += '<div class="text-sm py-6 text-center">暂无教室数据</div>'
  }

  return html
}

function renderTeacherAssignments(data) {
  return `<div class="text-sm">教师安排数据</div>`
}

// ------- Lifecycle -------
onMounted(() => {
  clockInterval = setInterval(updateClock, 1000)
  loadStats()
})

onUnmounted(() => {
  if (clockInterval) clearInterval(clockInterval)
})
</script>

<style scoped>
.dashboard {
  --bg-deep: #0a0e27;
  --bg-surface: #1a1f3a;
  --bg-card: rgba(26, 31, 58, 0.85);
  --border: rgba(100, 140, 255, 0.15);
  --accent: #4fc3f7;
  --accent2: #7c4dff;
  --green: #00e676;
  --yellow: #ffd740;
  --red: #ff5252;
  --orange: #ff9100;
  --text: #e0e0e0;
  --text-dim: rgba(224, 224, 224, 0.55);

  display: grid;
  grid-template-rows: auto auto 1fr auto;
  grid-template-columns: 1fr;
  gap: 20px;
  padding: 20px 28px 28px;
  min-height: 100vh;
  position: relative;
  z-index: 1;
  background: linear-gradient(160deg, #0a0e27 0%, #1a1f3a 100%);
  color: #e0e0e0;
}

.dashboard::before {
  content: '';
  position: fixed;
  inset: 0;
  background:
    linear-gradient(rgba(79,195,247,0.04) 1px, transparent 1px),
    linear-gradient(90deg, rgba(79,195,247,0.04) 1px, transparent 1px);
  background-size: 60px 60px;
  pointer-events: none;
  z-index: 0;
}

/* Header */
.header {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 18px;
  padding: 18px 0 8px;
  position: relative;
  z-index: 1;
}
.header::after {
  content: '';
  position: absolute;
  bottom: 0; left: 10%; right: 10%;
  height: 1px;
  background: linear-gradient(90deg, transparent, #4fc3f7, transparent);
}
.header-title {
  font-size: 1.65rem;
  font-weight: 700;
  letter-spacing: 6px;
  background: linear-gradient(90deg, #4fc3f7, #7c4dff);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.header-time {
  position: absolute;
  right: 4px;
  font-size: 0.85rem;
  color: rgba(224, 224, 224, 0.55);
  font-variant-numeric: tabular-nums;
}

/* KPI Row */
.kpi-row {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 16px;
  position: relative;
  z-index: 1;
}
@media (max-width: 1200px) { .kpi-row { grid-template-columns: repeat(3, 1fr); } }
@media (max-width: 640px) { .kpi-row { grid-template-columns: repeat(2, 1fr); } }

.kpi-card {
  background: rgba(26, 31, 58, 0.85);
  border: 1px solid rgba(100, 140, 255, 0.15);
  border-radius: 14px;
  padding: 18px 16px 14px;
  display: flex;
  flex-direction: column;
  align-items: center;
  position: relative;
  overflow: hidden;
  transition: transform 0.25s, box-shadow 0.25s;
}
.kpi-card:hover {
  transform: translateY(-3px) scale(1.02);
  box-shadow: 0 0 15px rgba(79, 195, 247, 0.35), 0 0 40px rgba(79, 195, 247, 0.12);
}
.kpi-card::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 3px;
  border-radius: 14px 14px 0 0;
}
.kpi-card.blue::before   { background: linear-gradient(90deg, #4fc3f7, transparent); }
.kpi-card.purple::before { background: linear-gradient(90deg, #7c4dff, transparent); }
.kpi-card.green::before  { background: linear-gradient(90deg, #00e676, transparent); }
.kpi-card.yellow::before { background: linear-gradient(90deg, #ffd740, transparent); }
.kpi-card.red::before    { background: linear-gradient(90deg, #ff5252, transparent); }
.kpi-card.orange::before { background: linear-gradient(90deg, #ff9100, transparent); }

.kpi-label {
  font-size: 0.75rem;
  color: rgba(224, 224, 224, 0.55);
  letter-spacing: 1px;
  margin-bottom: 8px;
  text-align: center;
}
.kpi-value {
  font-size: 2rem;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
  line-height: 1;
}
.kpi-card.blue   .kpi-value { color: #4fc3f7; }
.kpi-card.purple .kpi-value { color: #7c4dff; }
.kpi-card.green  .kpi-value { color: #00e676; }
.kpi-card.yellow .kpi-value { color: #ffd740; }
.kpi-card.red    .kpi-value { color: #ff5252; }
.kpi-card.orange .kpi-value { color: #ff9100; }

.kpi-unit {
  font-size: 0.8rem;
  font-weight: 400;
  opacity: 0.7;
}
.kpi-sub {
  font-size: 0.7rem;
  color: rgba(224, 224, 224, 0.55);
  margin-top: 6px;
}

.kpi-card.alert-pulse {
  animation: pulse-glow 2s ease-in-out infinite;
}
@keyframes pulse-glow {
  0%, 100% { box-shadow: 0 0 0 0 rgba(255,82,82,0); }
  50%      { box-shadow: 0 0 18px rgba(255,82,82,0.55), 0 0 50px rgba(255,82,82,0.2); }
}

/* Middle Section */
.middle {
  display: grid;
  grid-template-columns: 1fr 320px;
  gap: 20px;
  min-height: 380px;
  position: relative;
  z-index: 1;
}
@media (max-width: 980px) {
  .middle { grid-template-columns: 1fr; }
}

/* Chat Assistant Wrap */
.chart-3d-wrap {
  background: rgba(26, 31, 58, 0.85);
  border: 1px solid rgba(100, 140, 255, 0.15);
  border-radius: 14px;
  padding: 24px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.chart-3d-title {
  font-size: 0.85rem;
  color: rgba(224, 224, 224, 0.55);
  letter-spacing: 2px;
  margin-bottom: 18px;
  display: flex;
  align-items: center;
  gap: 8px;
}

/* Chat Body */
.chat-body {
  flex: 1;
  overflow-y: auto;
  padding: 8px 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.chat-welcome {
  display: flex;
  justify-content: flex-start;
}
.welcome-bubble {
  max-width: 95%;
  padding: 12px 16px;
  border-radius: 12px;
  border-bottom-left-radius: 4px;
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(79,195,247,0.2);
}

.chat-message {
  display: flex;
}
.chat-message.user {
  justify-content: flex-end;
}
.chat-message.assistant {
  justify-content: flex-start;
}
.message-bubble {
  max-width: 80%;
  padding: 10px 14px;
  border-radius: 12px;
  word-break: break-word;
}
.message-bubble.user {
  background: rgba(79,195,247,0.3);
  color: white;
  border-bottom-right-radius: 4px;
}
.message-bubble.assistant {
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(255,255,255,0.1);
  border-bottom-left-radius: 4px;
  color: #e0e0e0;
}

.chat-icon {
  color: #4fc3f7;
  margin-top: 2px;
  flex-shrink: 0;
}

/* Quick Prompts */
.quick-prompt {
  font-size: 12px;
  color: #4fc3f7;
  background: rgba(79,195,247,0.1);
  padding: 4px 8px;
  border-radius: 4px;
  cursor: pointer;
  transition: background 0.15s;
  display: flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 4px;
}
.quick-prompt:hover {
  background: rgba(79,195,247,0.2);
}

/* Typing Indicator */
.typing-indicator {
  display: flex;
  align-items: center;
  gap: 4px;
}
.typing-indicator span {
  width: 6px;
  height: 6px;
  background: rgba(224,224,224,0.6);
  border-radius: 50%;
  animation: typing 1.2s infinite;
}
.typing-indicator span:nth-child(2) { animation-delay: 0.2s; }
.typing-indicator span:nth-child(3) { animation-delay: 0.4s; }
@keyframes typing {
  0%, 60%, 100% { transform: translateY(0); opacity: 0.4; }
  30% { transform: translateY(-6px); opacity: 1; }
}

/* Chat Input */
.chat-input-area {
  padding: 12px 0 0;
  border-top: 1px solid rgba(100, 140, 255, 0.15);
}
.chat-input-wrap {
  display: flex;
  gap: 8px;
}
.chat-input {
  flex: 1;
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(100, 140, 255, 0.2);
  border-radius: 8px;
  padding: 8px 12px;
  color: #e0e0e0;
  font-size: 14px;
  outline: none;
  transition: border-color 0.2s;
}
.chat-input:focus {
  border-color: #4fc3f7;
}
.chat-input::placeholder {
  color: rgba(224, 224, 224, 0.3);
}
.chat-send-btn {
  background: linear-gradient(135deg, #4fc3f7, #7c4dff);
  border: none;
  border-radius: 8px;
  padding: 8px 12px;
  color: white;
  cursor: pointer;
  transition: opacity 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}
.chat-send-btn:hover:not(:disabled) {
  opacity: 0.85;
}
.chat-send-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

/* Gauge Panel */
.gauge-panel {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.gauge-card {
  flex: 1;
  background: rgba(26, 31, 58, 0.85);
  border: 1px solid rgba(100, 140, 255, 0.15);
  border-radius: 14px;
  padding: 18px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  position: relative;
  overflow: hidden;
}
.gauge-card h4 {
  font-size: 0.75rem;
  color: rgba(224, 224, 224, 0.55);
  letter-spacing: 1px;
  margin-bottom: 12px;
}

/* Ring */
.ring-container {
  position: relative;
  width: 150px;
  height: 150px;
}
.ring-container svg {
  width: 100%;
  height: 100%;
  transform: rotate(-90deg);
}
.ring-bg {
  fill: none;
  stroke: rgba(255,255,255,0.06);
  stroke-width: 12;
}
.ring-fg {
  fill: none;
  stroke-width: 12;
  stroke-linecap: round;
  stroke-dasharray: 389.56;
  stroke-dashoffset: 389.56;
  transition: stroke-dashoffset 1.8s cubic-bezier(0.22,1,0.36,1);
  filter: drop-shadow(0 0 6px var(--ring-color));
}
.ring-fg.blue   { stroke: url(#gradBlue);   --ring-color: rgba(79,195,247,0.6); }
.ring-fg.green  { stroke: url(#gradGreen);  --ring-color: rgba(0,230,118,0.6); }

.ring-value {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.ring-value .num {
  font-size: 1.6rem;
  font-weight: 700;
  font-variant-numeric: tabular-nums;
}
.ring-value .num.blue   { color: #4fc3f7; }
.ring-value .num.green  { color: #00e676; }
.ring-value .lbl {
  font-size: 0.65rem;
  color: rgba(224, 224, 224, 0.55);
}

.ring-spin svg {
  animation: ring-rotate 8s linear infinite;
}
@keyframes ring-rotate {
  from { transform: rotate(-90deg) rotate(0deg); }
  to   { transform: rotate(-90deg) rotate(360deg); }
}

/* Bottom - Quick Actions */
.trend-wrap {
  background: rgba(26, 31, 58, 0.85);
  border: 1px solid rgba(100, 140, 255, 0.15);
  border-radius: 14px;
  padding: 20px 24px;
  overflow: hidden;
  position: relative;
  z-index: 1;
}
.trend-title {
  font-size: 0.8rem;
  color: rgba(224, 224, 224, 0.55);
  letter-spacing: 2px;
  margin-bottom: 14px;
}

.quick-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}
.quick-action-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 20px;
  border-radius: 10px;
  border: 1px solid rgba(100, 140, 255, 0.2);
  background: rgba(255,255,255,0.03);
  color: #e0e0e0;
  font-size: 14px;
  cursor: pointer;
  transition: all 0.25s;
}
.quick-action-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 0 15px rgba(79, 195, 247, 0.35);
}
.quick-action-btn.blue   { border-color: rgba(79,195,247,0.3); }
.quick-action-btn.blue:hover   { background: rgba(79,195,247,0.15); }
.quick-action-btn.green  { border-color: rgba(0,230,118,0.3); }
.quick-action-btn.green:hover  { background: rgba(0,230,118,0.15); }
.quick-action-btn.yellow { border-color: rgba(255,215,64,0.3); }
.quick-action-btn.yellow:hover { background: rgba(255,215,64,0.15); }
.quick-action-btn.purple { border-color: rgba(124,77,255,0.3); }
.quick-action-btn.purple:hover { background: rgba(124,77,255,0.15); }
.quick-action-btn.orange { border-color: rgba(255,145,0,0.3); }
.quick-action-btn.orange:hover { background: rgba(255,145,0,0.15); }

/* Scrollbar */
.chat-body::-webkit-scrollbar { width: 6px; }
.chat-body::-webkit-scrollbar-track { background: transparent; }
.chat-body::-webkit-scrollbar-thumb { background: #7c4dff; border-radius: 3px; }
</style>

// app_react/src/pages/DashboardView.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Play,
  BarChart3,
  Edit3,
  Upload,
  Settings,
  Send,
  Bot,
  User,
  CheckCircle2,
  AlertTriangle,
} from 'lucide-react';
import RollingNumber from '@/components/RollingNumber';
import { useKPIData, type KPIDataItem } from '@/hooks/useKPIData';
import { chat, type ChatMessage as ChatMsgType } from '@/api/chat';
import type { ChatMessage } from '@/types';
import MarkdownIt from 'markdown-it';

// Markdown 渲染器（组件外部单例，避免重复创建）
const md = new MarkdownIt({
  html: true,
  breaks: true,
  linkify: true,
});

const kpiColors: Record<string, { bg: string; text: string; glow?: string }> = {
  blue: { bg: 'rgba(99, 149, 195, 0.08)', text: '#6395C3' },
  green: { bg: 'rgba(107, 155, 138, 0.08)', text: '#6B9B8A' },
  purple: { bg: 'rgba(156, 129, 175, 0.08)', text: '#9C81AF' },
  red: { bg: 'rgba(194, 122, 99, 0.08)', text: '#C27A63', glow: 'rgba(194, 122, 99, 0.15)' },
  yellow: { bg: 'rgba(197, 172, 116, 0.08)', text: '#C5AC74' },
  orange: { bg: 'rgba(200, 145, 107, 0.08)', text: '#C9916B' },
};

const quickActions = [
  { label: '开始排考', path: '/scheduler', icon: Play, color: '#6395C3' },
  { label: '查看结果', path: '/results', icon: BarChart3, color: '#6B9B8A' },
  { label: '手动微调', path: '/adjustments', icon: Edit3, color: '#C5AC74' },
  { label: '导入数据', path: '/import-export', icon: Upload, color: '#9C81AF' },
  { label: '基础数据', path: '/base-data', icon: Settings, color: '#C9916B' },
];

export default function DashboardView() {
  const navigate = useNavigate();
  const [clock, setClock] = useState(new Date());
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isBackendOnline, setIsBackendOnline] = useState(true);  // 后端服务状态
  const chatEndRef = useRef<HTMLDivElement>(null);
  const { kpiData, loading: kpiLoading } = useKPIData();

  // 检测后端服务状态
  const checkBackendStatus = useCallback(async () => {
    try {
      const response = await fetch('/api/chat/status', {
        method: 'GET',
        signal: AbortSignal.timeout(3000),  // 3秒超时
      });
      setIsBackendOnline(response.ok);
    } catch (error) {
      setIsBackendOnline(false);
    }
  }, []);

  // 初始检测 + 定期轮询（每30秒）
  useEffect(() => {
    checkBackendStatus();
    const interval = setInterval(checkBackendStatus, 30000);
    return () => clearInterval(interval);
  }, [checkBackendStatus]);

  // 添加欢迎消息
  useEffect(() => {
    if (chatMessages.length === 0) {
      setChatMessages([{
        id: 'welcome',
        role: 'assistant',
        content: '您好！我是排考小助手。我可以帮您查询教室、安排考试等。请问有什么可以帮您的吗？',
        timestamp: new Date(),
      }]);
    }
  }, []);

  useEffect(() => {
    const timer = setInterval(() => setClock(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const formatClock = (date: Date) => {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    const h = String(date.getHours()).padStart(2, '0');
    const min = String(date.getMinutes()).padStart(2, '0');
    const s = String(date.getSeconds()).padStart(2, '0');
    return { dateStr: `${y}-${m}-${d}`, timeStr: `${h}:${min}:${s}` };
  };

  const { dateStr, timeStr } = formatClock(clock);

  const handleSendMessage = () => {
    if (!inputValue.trim()) return;

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue,
      timestamp: new Date(),
    };

    setChatMessages((prev) => [...prev, userMsg]);
    setInputValue('');
    setIsTyping(true);

    // 调用真实聊天 API
    const cleanup = chat(
      { message: inputValue },
      // onMessage callback
      (partialMessage) => {
        setChatMessages((prev) => {
          const lastMsg = prev[prev.length - 1];
          if (lastMsg && lastMsg.role === 'assistant' && !lastMsg.id.startsWith('done-')) {
            // 更新最后一条助手消息
            const updated = [...prev];
            updated[updated.length - 1] = {
              ...lastMsg,
              content: (lastMsg.content || '') + (partialMessage.content || ''),
            };
            return updated;
          } else {
            // 添加新消息
            const newMsg: ChatMessage = {
              id: `assistant-${Date.now()}`,
              role: 'assistant',
              content: partialMessage.content || '',
              timestamp: new Date(),
            };
            return [...prev, newMsg];
          }
        });
      },
      // onError callback
      (error) => {
        console.error('Chat error:', error);
        setIsTyping(false);
        setChatMessages((prev) => [
          ...prev,
          {
            id: `error-${Date.now()}`,
            role: 'assistant',
            content: '抱歉，聊天服务暂时不可用，请稍后再试。',
            timestamp: new Date(),
          },
        ]);
      },
      // onComplete callback
      () => {
        setIsTyping(false);
      }
    );
  };

  return (
    <div className="page-container px-4 md:px-6">
      {/* Background grid pattern */}
      <div
        className="absolute inset-0 opacity-30 dark:opacity-[0.07] pointer-events-none"
        style={{
          backgroundImage: `url('/images/dashboard-bg.jpg')`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      />

      <div className="relative max-w-[1400px] mx-auto space-y-6 md:space-y-8">
        {/* Header */}
        <div className="text-center py-4 md:py-6">
          <h1 className="font-display text-2xl md:text-4xl font-semibold text-[#1F2328] dark:text-[#E6EDF3] tracking-wider mb-3">
            考务监控指挥中心
          </h1>
          <div className="flex items-center justify-center gap-2">
            <span className="text-xs md:text-sm text-[#8C959F] dark:text-[#8B949E]">{dateStr}</span>
            <span className="font-mono text-base md:text-lg text-[#1F2328] dark:text-[#E6EDF3] tracking-wider">
              {timeStr}
              <span className="animate-pulse-soft text-[#D4A373]">:</span>
              <span className="text-[#8C959F] dark:text-[#8B949E]">{timeStr.slice(-2)}</span>
            </span>
          </div>
        </div>

        {/* KPI Row */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-4">
          {kpiLoading ? (
            // 加载状态
            Array.from({ length: 7 }).map((_, index) => (
              <div key={index} className="glass-card rounded-3xl p-5 animate-pulse">
                <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-20 mb-2"></div>
                <div className="h-8 bg-gray-200 dark:bg-gray-700 rounded w-16"></div>
              </div>
            ))
          ) : (
            kpiData.map((kpi, index) => {
              const colors = kpiColors[kpi.color];
              return (
                <div
                  key={index}
                  className={`glass-card rounded-3xl p-5 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl ${
                    kpi.hasAlert ? 'animate-pulse' : ''
                  }`}
                  style={{
                    backgroundColor: colors.bg,
                    ...(kpi.hasAlert
                      ? { animation: 'alert-pulse 2s ease-in-out infinite' }
                      : {}),
                  }}
                >
                  <div className="text-xs text-[#8C959F] dark:text-[#8B949E] mb-2">{kpi.label}</div>
                  <div className="flex items-baseline gap-1">
                    <span
                      className="font-display text-3xl font-semibold"
                      style={{ color: colors.text }}
                    >
                      <RollingNumber
                        target={kpi.value}
                        decimals={kpi.unit === '%' ? 1 : 0}
                      />
                    </span>
                    <span className="text-sm text-[#8C959F] dark:text-[#8B949E]">{kpi.unit}</span>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Middle Section: Chat + Gauges */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-4 md:gap-6">
          {/* Chat Assistant */}
          <div className="glass-card rounded-3xl overflow-hidden flex flex-col" style={{ minHeight: 624 }}>
            <div className="px-6 py-4 border-b border-[#F3F4F6] dark:border-[#30363D] flex items-center gap-2">
              <Bot size={18} className="text-[#D4A373]" />
              <span className="font-display text-base font-medium text-[#1F2328] dark:text-[#E6EDF3]">
                排考小助手
              </span>
              <span className={`ml-2 px-2 py-0.5 rounded-full text-xs font-medium ${isBackendOnline ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}`}>
                <span className={`inline-block w-1.5 h-1.5 rounded-full mr-1 ${isBackendOnline ? 'bg-green-500' : 'bg-gray-400'}`} />
                {isBackendOnline ? '在线' : '离线'}
              </span>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4" style={{ maxHeight: 576 }}>
              {chatMessages.map((msg) => (
                <div
                  key={msg.id}
                  className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
                >
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                      msg.role === 'assistant'
                        ? 'bg-[#D4A373]/10'
                        : 'bg-[#334155]'
                    }`}
                  >
                    {msg.role === 'assistant' ? (
                      <Bot size={14} className="text-[#D4A373]" />
                    ) : (
                      <User size={14} className="text-white" />
                    )}
                  </div>
                  <div
                    className={`max-w-[70%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                      msg.role === 'assistant'
                        ? 'bg-[#F9FAFB] dark:bg-[#21262D] text-[#1F2328] dark:text-[#E6EDF3]'
                        : 'text-white'
                    }`}
                    style={
                      msg.role === 'user'
                        ? { background: 'linear-gradient(135deg, #D4A373 0%, #C9956B 100%)' }
                        : {}
                    }
                  >
                    {msg.role === 'assistant' ? (
                      <div
                        className="markdown-body"
                        dangerouslySetInnerHTML={{ __html: md.render(msg.content || '') }}
                      />
                    ) : (
                      msg.content
                    )}
                  </div>
                </div>
              ))}
              {isTyping && (
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-full bg-[#D4A373]/10 flex items-center justify-center flex-shrink-0">
                    <Bot size={14} className="text-[#D4A373]" />
                  </div>
                  <div className="bg-[#F9FAFB] dark:bg-[#21262D] rounded-2xl px-4 py-3">
                    <div className="flex gap-1">
                      <span className="w-2 h-2 rounded-full bg-[#C8CDD3] animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-2 h-2 rounded-full bg-[#C8CDD3] animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-2 h-2 rounded-full bg-[#C8CDD3] animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            <div className="px-4 py-3 border-t border-[#F3F4F6] dark:border-[#30363D]">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                  placeholder="输入您的问题..."
                  className="form-input-glass flex-1 rounded-xl"
                />
                <button
                  onClick={handleSendMessage}
                  className="btn-amber w-10 h-10 flex items-center justify-center rounded-xl p-0"
                >
                  <Send size={16} />
                </button>
              </div>
            </div>
          </div>

          {/* Gauge Panel */}
          <div className="space-y-4">
            <div className="glass-card rounded-3xl p-6">
              <h3 className="font-display text-sm font-medium text-[#8C959F] dark:text-[#8B949E] mb-4 text-center">
                排考完成度
              </h3>
              <div className="flex flex-col items-center">
                {kpiLoading ? (
                  <div className="animate-pulse">
                    <div className="h-40 w-40 bg-gray-200 dark:bg-gray-700 rounded-full"></div>
                  </div>
                ) : (
                  (() => {
                    const kpi = kpiData.find(p => p.label === '已安排考试场次');
                    const pendingKpi = kpiData.find(p => p.label === '未安排考试场次');
                    const scheduled = kpi?.value || 0;
                    const pending = pendingKpi?.value || 0;
                    const total = scheduled + pending;
                    const percentage = total > 0 ? Math.round(scheduled / total * 100) : 0;
                    const radius = 70;
                    const circumference = 2 * Math.PI * radius;
                    const progress = (percentage / 100) * circumference;
                    
                    return (
                      <>
                        <svg width="180" height="180" viewBox="0 0 180 180">
                          <circle cx="90" cy="90" r={radius} fill="none" stroke="#F3F4F6" strokeWidth="10" />
                          <circle
                            cx="90"
                            cy="90"
                            r={radius}
                            fill="none"
                            stroke="#D4A373"
                            strokeWidth="10"
                            strokeLinecap="round"
                            strokeDasharray={`${progress} ${circumference}`}
                            strokeDashoffset={0}
                            transform="rotate(-90 90 90)"
                            style={{ filter: 'drop-shadow(0 2px 6px rgba(212, 163, 115, 0.3))' }}
                          />
                          <text x="90" y="82" textAnchor="middle" className="font-display text-3xl font-semibold fill-[#1F2328] dark:fill-[#E6EDF3]">
                            {percentage}%
                          </text>
                          <text x="90" y="105" textAnchor="middle" className="text-xs fill-[#8C959F] dark:fill-[#8B949E]">
                            已排考 {scheduled}/{total} 场
                          </text>
                        </svg>
                      </>
                    );
                  })()
                )}
              </div>
            </div>

            <div className="glass-card rounded-3xl p-6">
              <h3 className="font-display text-sm font-medium text-[#8C959F] dark:text-[#8B949E] mb-4 text-center">
                冲突检测状态
              </h3>
              {kpiLoading ? (
                <div className="animate-pulse space-y-3">
                  <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-20 mx-auto"></div>
                  <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
                  <div className="h-3 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
                </div>
              ) : (
                (() => {
                  const conflictKpi = kpiData.find(p => p.label === '排考冲突告警');
                  const conflictCount = conflictKpi?.value || 0;
                  
                  return (
                    <div className="flex flex-col items-center gap-3">
                      <div className="flex items-center gap-2">
                        <AlertTriangle size={20} className={conflictCount > 0 ? "text-[#C27A63]" : "text-[#6B9B8A]"} />
                        <span className={`font-display text-2xl font-semibold ${conflictCount > 0 ? "text-[#C27A63]" : "text-[#6B9B8A]"}`}>
                          {conflictCount}
                        </span>
                        <span className="text-sm text-[#8C959F] dark:text-[#8B949E]">项冲突</span>
                      </div>
                      {conflictCount > 0 ? (
                        <div className="w-full space-y-2">
                          <div className="flex items-center gap-2 text-xs text-[#8C959F] dark:text-[#8B949E]">
                            <span className="w-2 h-2 rounded-full bg-[#C27A63]"></span>
                            教室冲突: {Math.ceil(conflictCount * 0.67)}项
                        </div>
                          <div className="flex items-center gap-2 text-xs text-[#8C959F] dark:text-[#8B949E]">
                            <span className="w-2 h-2 rounded-full bg-[#C5AC74]"></span>
                            教师冲突: {Math.floor(conflictCount * 0.33)}项
                        </div>
                        </div>
                      ) : (
                        <div className="flex items-center gap-1.5 text-xs text-[#6B9B8A]">
                          <CheckCircle2 size={14} />
                          暂无冲突
                        </div>
                      )}
                    </div>
                  );
                })()
              )}
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3 md:gap-4">
          {quickActions.map((action, index) => {
            const Icon = action.icon;
            return (
              <button
                key={index}
                onClick={() => navigate(action.path)}
                className="glass-card rounded-3xl p-6 text-left transition-all duration-300 hover:-translate-y-1 group cursor-pointer"
                style={{
                  boxShadow: '0 4px 24px rgba(0,0,0,0.04)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.boxShadow = `0 8px 32px ${action.color}20, 0 4px 16px ${action.color}15`;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.boxShadow = '0 4px 24px rgba(0,0,0,0.04)';
                }}
              >
                <div
                  className="w-12 h-12 rounded-2xl flex items-center justify-center mb-4 transition-all duration-300 group-hover:scale-110"
                  style={{ backgroundColor: `${action.color}12` }}
                >
                  <Icon size={22} style={{ color: action.color }} />
                </div>
                <span className="font-display text-base font-medium text-[#1F2328] dark:text-[#E6EDF3] group-hover:text-[#D4A373] transition-colors">
                  {action.label}
                </span>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}
